receivers:
  filelog:
    # include: [/var/log/*.log]
    # include: [/var/log/messages, /var/log/syslog, /var/log/user.log]
    # include: [/var/log/messages, /var/log/syslog, /var/log/*.log]
    include: [/var/jenkins_home/jobs/**/log]

processors:
 attributes:
   actions:
     - action: insert
       key: log_file_name
       from_attribute: log.file.name
     - action: insert
       key: loki.attribute.labels
       value: log_file_name

exporters:
  loki:
    endpoint: "http://host.docker.internal:3100/loki/api/v1/push"
  logging:
    # logLevel: info

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [attributes]
      exporters: [logging, loki]
